# Generated by Django 5.0.6 on 2024-05-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.IntegerField(help_text='Glucose level')),
                ('blood_pressure', models.IntegerField(help_text='Blood pressure')),
                ('skin_thickness', models.IntegerField(help_text='Skin thickness')),
                ('insulin', models.IntegerField(help_text='Insulin level')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('diabetes_pedigree_function', models.FloatField(help_text='Diabetes pedigree function')),
                ('age', models.IntegerField(help_text='Age')),
                ('outcome', models.BooleanField(default=False, help_text='Diagnosed diabetes')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('glucose', models.IntegerField(help_text='Glucose level')),
                ('blood_pressure', models.IntegerField(help_text='Blood pressure')),
                ('skin_thickness', models.IntegerField(help_text='Skin thickness')),
                ('insulin', models.IntegerField(help_text='Insulin level')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('diabetes_pedigree_function', models.FloatField(help_text='Diabetes pedigree function')),
                ('age', models.IntegerField(help_text='Age of the patient')),
                ('outcome', models.BooleanField(default=False, help_text='Diabetes prediction outcome')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
